--------------------------------------------------------
--  已建立�?��?? - ??��?��??-三�??-21-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CART_TNO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GROUP18"."CART_TNO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MEMBER_MID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GROUP18"."MEMBER_MID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ORDER_OID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GROUP18"."ORDER_OID_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 9 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CART
--------------------------------------------------------

  CREATE TABLE "GROUP18"."SELECTJOURNEY" 
   (	"MID" VARCHAR2(26 BYTE), 
	"CARTTIME" VARCHAR2(26 BYTE), 
	"TNO" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "GROUP18"."MEMBER" 
   (	"MID" VARCHAR2(38 BYTE), 
	"NAME" VARCHAR2(128 BYTE), 
	"ACCOUNT" VARCHAR2(128 BYTE), 
	"PASSWORD" VARCHAR2(128 BYTE), 
	"IDENTITY" VARCHAR2(128 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDER_LIST
--------------------------------------------------------

  CREATE TABLE "GROUP18"."ORDER_LIST" 
   (	"OID" NUMBER(38,0), 
	"MID" NUMBER(38,0), 
	"ORDERTIME" DATE, 
	"PRICE" NUMBER(38,0), 
	"TNO" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JOURNEY
--------------------------------------------------------

  CREATE TABLE "GROUP18"."JOURNEY" 
   (	"PID" VARCHAR2(26 BYTE), 
	"PNAME" VARCHAR2(128 BYTE), 
	"PRICE" NUMBER(38,0), 
	"CATEGORY" VARCHAR2(128 BYTE), 
	"PDESC" VARCHAR2(1024 BYTE), 
	"PIMAGE" VARCHAR2(1024 BYTE), 
	"PIMAGE2" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECORD
--------------------------------------------------------

   CREATE TABLE "GROUP18"."RECORD" 
   (	"TNO" NUMBER(38,0), 
	"PID" VARCHAR2(26 BYTE), 
	"AMOUNT" NUMBER(38,0), 
	"SALEPRICE" NUMBER(38,0), 
	"TOTAL" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger MEMBER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GROUP18"."MEMBER_TRG" 
BEFORE INSERT ON member  
FOR EACH ROW  
BEGIN  
IF :new.mid IS NULL THEN  
SELECT member_mid_seq.nextval INTO :new.mid FROM dual;  
END IF;  
END;

/
ALTER TRIGGER "GROUP18"."MEMBER_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDER_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "GROUP18"."ORDER_TRG" 
BEFORE INSERT ON order_list  
FOR EACH ROW  
BEGIN  
IF :new.oid IS NULL THEN  
SELECT order_oid_seq.nextval INTO :new.oid FROM dual;  
END IF;  
END;

/
ALTER TRIGGER "GROUP18"."ORDER_TRG" ENABLE;
